name: development

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm ci

      - name: Set environment
        run: cp .env.example .env

      - name: Unit tests
        run: echo no unit tests

      - name: Integration tests
        run: echo no integration tests